import { useRef, useState } from 'react'
import { AnimatePresence, motion, useScroll, useTransform } from 'motion/react'
import { ArrowDown, ArrowRight, ArrowUpRight, ChevronDown, Layers3, Menu, MoveUpRight, Plus, Sparkles, X } from 'lucide-react'
import { Logo } from '../components/Logo'
import { Reveal } from '../components/Reveal'
import '../components/cta.css'
import '../components/nav-fix.css'

const industries = [
  ['food', 'Food', 'Taste, made visible.'], ['fashion', 'Fashion', 'Culture in motion.'], ['real-estate', 'Real Estate', 'Spaces with gravity.'], ['fitness', 'Fitness', 'Energy that moves.'],
  ['dental', 'Dental', 'Confidence, considered.'], ['hotel', 'Hotel', 'Stay a little longer.'], ['saas', 'SaaS', 'Complexity, clarified.'], ['automotive', 'Automotive', 'Move with intent.'],
]
const services = [['01', 'Digital Marketing', 'We build growth systems that make your next move feel obvious.'], ['02', 'Google & Meta Ads', 'Paid campaigns with a point of view, measured from first impression to action.'], ['03', 'SEO', 'Search foundations that make the right people find you at the right moment.'], ['04', 'Web Development', 'Websites with a pulse, a point of view, and a reason to return.'], ['05', 'AI Integration', 'Practical intelligence woven into the places your team already works.'], ['06', 'Automation', 'Small systems that remove friction and give your team room to think.']]
const faqs = [['What is Rabina?', 'Rabina is a digital growth studio building distinctive web, brand, and AI experiences for companies with ambition.'], ['Do you work across industries?', 'Yes. Our approach is adaptable, but never generic. Explore the industry demos to see how the same thinking becomes a different world.'], ['Can we work together on a specific project?', 'Yes. From a focused web build to an ongoing growth partnership, we shape the engagement around the challenge.']]

function scrollToSection(id: string) {
  document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' })
}

export function Navigation() {
  const [open, setOpen] = useState(false)
  return <header className="site-nav"><div className="nav-inner"><Logo /><button className="mobile-menu" aria-label={open ? 'Close menu' : 'Open menu'} onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button><nav className={open ? 'nav-open' : ''}><a href="/?returnTo=capability" onClick={() => setOpen(false)}>Capabilities</a><a href="/?returnTo=services" onClick={() => setOpen(false)}>Services</a><a href="/?returnTo=showcase" onClick={() => setOpen(false)}>Showcase</a><a href="/?returnTo=industries" onClick={() => setOpen(false)}>Industries</a><a className="nav-talk" href="/?returnTo=contact" onClick={() => setOpen(false)}>Start a project <ArrowUpRight size={14} /></a></nav></div></header>
}

export function Hero() {
  const { scrollY } = useScroll(); const y = useTransform(scrollY, [0, 650], [0, 180]); const scale = useTransform(scrollY, [0, 650], [1, 1.18])
  return <section className="home-hero"><motion.div className="hero-image" style={{ y, scale }} /><div className="hero-overlay" /><div className="hero-content"><p className="kicker light hero-kicker">DIGITAL GROWTH. WEB. AI.</p><h1><motion.span initial={{ opacity: 0, x: -25 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: .8, delay: .12 }}>Make a mark</motion.span><motion.span initial={{ opacity: 0, x: 28 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: .9, delay: .25 }}><i>that moves.</i></motion.span></h1><motion.p className="hero-intro" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: .8, delay: .52 }}>Rabina creates digital experiences for brands ready to change the conversation.</motion.p><motion.a className="circle-cta" href="/" onClick={(event) => { event.preventDefault(); scrollToSection('capability') }} aria-label="Explore Rabina" animate={{ y: [0, 5, 0] }} transition={{ duration: 3, repeat: Infinity, ease: 'easeInOut' }}><ArrowDown /></motion.a></div><motion.div className="hero-side-note" initial={{ opacity: 0, x: 15 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: .7, duration: .6 }}>01 — 08<br /><span>Scroll to explore</span></motion.div></section>
}

export function Capability() { return <section className="capability section" id="capability"><div className="wide-statement"><Reveal mode="left"><p className="kicker">OUR POINT OF VIEW</p><h2>Growth is not<br /><i>a number.</i></h2><p className="statement-copy">It is a feeling. The feeling when your website finally sounds like you. When your customer gets it. When the next step becomes the only step.</p></Reveal></div><div className="capability-visual"><span>Rabina / 2026</span><motion.div whileHover={{ rotate: 8, scale: 1.05 }} className="monogram">R<span>/</span></motion.div><p>Ideas with<br />somewhere to go.</p></div></section> }

export function Services() { const stageRef = useRef<HTMLElement>(null); const { scrollYProgress } = useScroll({ target: stageRef, offset: ['start end', 'end start'] }); const serviceX = useTransform(scrollYProgress, [0.05, 0.8], ['0%', '-18%']); return <section className="services section" id="services" ref={stageRef}><div className="section-head"><p className="kicker">02 / CAPABILITIES</p><h2>We make<br /><i>meaningful</i> moves.</h2></div><div className="services-stage"><div className="services-sticky"><div className="services-rail"><motion.div className="services-track" style={{ x: serviceX }}>{services.map(([number, title, copy], index) => <a className={`service-panel service-panel-${index + 1}`} href="/?returnTo=contact" key={number}><span className="service-number">{number}</span><div><h3>{title}</h3><p>{copy}</p></div><ArrowUpRight /></a>)}</motion.div></div><div className="service-progress"><span>Scroll through the work</span><i /></div></div></div></section> }

export function Showcase() { const [active, setActive] = useState(0); const [direction, setDirection] = useState(1); const previews = [['hotel', 'Stay', 'in the moment.', 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=1800&q=85'], ['food', 'Taste', 'in motion.', 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1800&q=85'], ['fashion', 'Dress', 'the future.', 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1800&q=85']]; const item = previews[active]; const select = (index: number) => { setDirection(index >= active ? 1 : -1); setActive(index) }; return <section className="showcase" id="showcase"><motion.div className="showcase-panel" initial={{ clipPath: 'inset(0 100% 0 0)' }} whileInView={{ clipPath: 'inset(0 0% 0 0)' }} viewport={{ once: true }} transition={{ duration: 1.1, ease: [0.76, 0, 0.24, 1] }}><AnimatePresence initial={false} mode="sync"><motion.div key={item[0]} className="showcase-image-layer" initial={{ opacity: 0, scale: 1.08, x: direction * 80 }} animate={{ opacity: 1, scale: 1, x: 0 }} exit={{ opacity: 0, scale: .96, x: direction * -80 }} transition={{ duration: .75, ease: [0.22, 1, 0.36, 1] }} style={{ backgroundImage: `linear-gradient(90deg,rgba(0,0,0,.9),rgba(0,0,0,.15)),url(${item[3]})` }} /></AnimatePresence><div className="showcase-copy"><p className="kicker light">03 / SHOWCASE</p><AnimatePresence mode="wait" initial={false}><motion.h2 key={item[0]} initial={{ opacity: 0, x: direction * 35 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: direction * -35 }} transition={{ duration: .55 }}>{item[1]}<br /><i>{item[2]}</i></motion.h2></AnimatePresence><p>A brand world with a pulse. Digital presence, photography direction, and a journey built to be remembered.</p><a className="line-link light" href={`/demos/${item[0]}`}>Enter experience <ArrowUpRight size={16} /></a></div><div className="showcase-type">{item[1].toUpperCase()}<br /><span>{item[2].toUpperCase()}</span></div><div className="showcase-picker">{previews.map((preview, index) => <button className={active === index ? 'selected' : ''} key={preview[0]} onMouseEnter={() => select(index)} onFocus={() => select(index)} onClick={() => select(index)}><span>0{index + 1}</span>{preview[0]}</button>)}</div></motion.div></section> }

export function Industries() { const [active, setActive] = useState(0); const current = industries[active]; return <section className="industries section" id="industries"><div className="section-head industry-head"><div><p className="kicker">04 / INDUSTRIES</p><h2>Choose a world.<br /><i>Step inside.</i></h2></div><p>Eight distinct demo experiences. One Rabina point of view.</p></div><div className="industry-explorer" id="showcase-industries"><div className="industry-preview" style={{ backgroundImage: `linear-gradient(90deg,rgba(17,17,17,.5),transparent),url(https://images.unsplash.com/photo-${active === 0 ? '1515003197210-e0cd71810b5f' : active === 1 ? '1490481651871-ab68de25d43d' : active === 2 ? '1600607687920-4e2a09cf159d' : active === 3 ? '1534438327276-14e5300c3a48' : active === 4 ? '1609840114035-3c981b782dfe' : active === 5 ? '1564501049412-61c2a3083791' : active === 6 ? '1551434678-e076c223a692' : '1503376780353-7e6692767b70'}?auto=format&fit=crop&w=1000&q=80)` }}><span>Selected / {current[1]}</span><strong>{current[2]}</strong><a href={`/demos/${current[0]}`}>Open demo <ArrowUpRight size={16} /></a></div><div className="industry-list">{industries.map(([slug, title, sub], i) => <motion.a href={`/demos/${slug}`} className={`industry-row industry-${slug} ${active === i ? 'active' : ''}`} key={slug} onMouseEnter={() => setActive(i)} onFocus={() => setActive(i)} whileHover={{ paddingLeft: 28 }}><span>0{i + 1}</span><h3>{title}</h3><p>{sub}</p><MoveUpRight size={18} /></motion.a>)}</div></div></section> }

export function Why() { return <section className="why section"><div className="why-copy"><p className="kicker">05 / WHY RABINA</p><h2>We bring the<br /><i>outside in.</i></h2><p>Fresh perspective. Sharp execution. A team small enough to care about the details and experienced enough to know which ones matter.</p></div><div className="why-orbit"><div className="orbit-ring ring-a" /><div className="orbit-ring ring-b" /><div className="orbit-core"><Layers3 size={27} /><span>human<br />+ machine</span></div></div></section> }

export function Process() { return <section className="process section"><div className="section-head"><p className="kicker">06 / PROCESS</p><h2>Thoughtful by<br /><i>design.</i></h2></div><div className="process-steps">{[['01', 'Listen', 'We find the tension worth solving.'], ['02', 'Shape', 'We turn insight into a world people want to enter.'], ['03', 'Launch', 'We put it in motion, then keep learning.']].map(([num, title, text]) => <div className="process-step" key={num}><span>{num}</span><h3>{title}</h3><p>{text}</p><ArrowRight /></div>)}</div></section> }

export function AISection() { return <section className="ai-section"><div className="ai-grid-bg" /><div className="ai-copy"><p className="kicker light">07 / AI, WITH TASTE</p><h2>Smarter<br /><i>by nature.</i></h2><p>We use AI where it creates leverage, not noise. From intelligent content systems to living customer journeys, we help your business move at the speed of relevance.</p><a className="line-link light" href="/?returnTo=contact">Explore AI integration <ArrowUpRight size={16} /></a></div><motion.div className="ai-signal" animate={{ rotate: 360 }} transition={{ duration: 30, repeat: Infinity, ease: 'linear' }}><Sparkles size={28} /><span>signal<br />detected</span></motion.div><div className="ai-data"><span>RABINA INTELLIGENCE / ONLINE</span><strong>01.4</strong><small>Human context<br />is the advantage.</small></div></section> }

export function About() { return <section className="about section"><div className="about-image" /><div className="about-copy"><p className="kicker">08 / ABOUT</p><h2>The studio<br /><i>behind the shift.</i></h2><p>Rabina is a distributed studio of strategists, designers, developers, and curious people. We believe the best digital work has a point of view and leaves room for people to find their own.</p><a className="line-link" href="/?returnTo=contact">Meet Rabina <ArrowUpRight size={16} /></a></div></section> }

export function CTA() { const [submitted, setSubmitted] = useState(false); return <section className="final-cta" id="contact"><div className="cta-copy"><p className="kicker">LET&apos;S MAKE SOMETHING MATTER</p><h2>What are you<br /><i>moving toward?</i></h2><a className="big-cta" href="mailto:hello@rabina.studio">Start a conversation <ArrowUpRight /></a></div><form className="cta-form" onSubmit={(event) => { event.preventDefault(); setSubmitted(true) }}>{submitted ? <div className="cta-success"><span>01</span><h3>Message received.</h3><p>We&apos;ll be in touch within two working days.</p></div> : <><label>Name<input required type="text" placeholder="Your name" /></label><label>Email<input required type="email" placeholder="you@company.com" /></label><label>Tell us a little<textarea required rows={2} placeholder="The challenge, the idea, the next move..." /></label><button type="submit">Send it our way <ArrowUpRight size={16} /></button></>}</form></section> }

export function Footer() { return <footer className="footer"><div className="footer-top"><Logo inverse /><p>DIGITAL GROWTH.<br />WEB. AI.</p><div className="footer-contact"><a href="mailto:hello@rabina.studio">hello@rabina.studio</a><a href="https://www.instagram.com" target="_blank" rel="noreferrer">Instagram ↗</a><a href="https://www.linkedin.com" target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div><div className="footer-bottom"><span>© 2026 Rabina Studio</span><span>Built with intent.</span><a href="/">Back to top ↑</a></div></footer> }

export function FAQ() { const [open, setOpen] = useState(0); return <section className="faq section"><div><p className="kicker">A FEW ANSWERS</p><h2>Good to<br /><i>know.</i></h2></div><div className="faq-list">{faqs.map(([question, answer], i) => <div className="faq-item" key={question}><button onClick={() => setOpen(open === i ? -1 : i)}><span>{question}</span>{open === i ? <ChevronDown className="rotated" /> : <Plus />}</button>{open === i && <motion.p initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }}>{answer}</motion.p>}</div>)}</div></section> }
